#! /bin/bash
set -exo nounset

if test -f Makefile || test -f makefile ; then
	make distclean || make clean
fi
if test -f configure ; then
	./configure
	make distclean || make clean
fi

$CIS/autogen-$AUTOGEN

# TODO make a proper source release
if test x$SRC != x$REPO ; then
	rm $V -rf $SRC
	cp $V -a $REPO $SRC
	cd $SRC
fi

#(test ! -f Makefile && test ! -f makefile) || \
#make distclean || \
#make clean
#test ! -f configure || (./configure && make distclean)

if test x$BLD != x$SRC ; then
	rm $V -rf $BLD
	mkdir $V $BLD
	cd $BLD
fi

if   test -f $SRC/configure ; then CF=$SRC/configure
elif test -f $SRC/config ; then CF=$SRC/config
elif test -f $SRC/Config ; then CF=$SRC/Config
fi

# see what config options there are
#if test -f $SRC/configure ; then
if test ! -z {CF+x} ; then
	test -f $OPT.default || \
	$CF --help | sed s/^/#/ | \
	tee $OPT.default
	# set config options
	test -f $OPT || \
	(vi $OPT.default && cp $V $OPT{.default,})
	test -f $OPT
	# finally...
	#$CONFIGURE_ENV \

	$CF --prefix=$PREFIX $CONFIGURE_FLAGS `grep -v ^# $OPT`

	make
else
	if test -f $SRC/Makefile ; then
		MF=$SRC/Makefile
	elif test -f $SRC/makefile ; then
		MF=$SRC/makefile
	fi	
	if test ! -f $OPT ; then
		sed s/^#// $MF > $OPT
		vi $OPT
	fi
	make -f $MF `grep -v ^# $OPT`
fi

$CIS/install-$CIS_INSTALL
