#! /bin/sh
set -exo nounset

cd $PROJECT

if test -f Makefile || test -f makefile ; then
	make distclean || make clean
fi
if test -f configure ; then
	./configure
	make distclean || make clean
fi

$CIS/autogen-$AUTOGEN

# TODO make a proper source release
if test x$SRC != x$REPO ; then
	rm $V -rf $SRC
	cp $V -a $REPO $SRC
	cd $SRC
fi

#(test ! -f Makefile && test ! -f makefile) || \
#make distclean || \
#make clean
#test ! -f configure || (./configure && make distclean)

if test x$BLD != x$SRC ; then
	rm $V -rf $BLD
	mkdir $V $BLD
	cd $BLD
fi

# see what config options there are
if test -f $SRC/configure ; then
	test -f $OPT.default || \
	$SRC/configure --help | sed s/^/#/ | \
	tee $OPT.default
	# set config options
	test -f $OPT || \
	(vi $OPT.default && cp $V $OPT{.default,})
	test -f $OPT
	# finally...
	$SRC/configure `grep -v ^# $OPT`

	make
else
	if test ! -f $OPT ; then
		sed s/^#// Makefile > $OPT
		vi $OPT
	fi
	make `grep -v ^# $OPT` -C BaseTools
	export EDK_TOOLS_PATH=$REPO/edk2/BaseTools
	. ./edksetup.sh
	vi Conf/target.txt
	build
	test -f Build/MdeModule/DEBUG_*/*/HelloWorld.efi
fi

$CIS/install-$CIS_INSTALL
