#! /bin/bash
set -exo nounset

for k in -{pack,strip} '' ; do
	test -f $PKG$k.txz || continue
	tar ${V}xpf $PKG$k.txz -C /
	#tar ${V}xpf $PKG$k.txz -C /opt/cross/$TARGET_TYPE
	break
done

for k in -{zman,data} ; do
	test -f $PKG$k.txz || continue
	tar ${V}xpf $PKG$k.txz -C /
	#tar ${V}xpf $PKG$k.txz -C /opt/cross/$TARGET_TYPE
	break
done
