#! /bin/bash
set -exo nounset

for k in -{pack,strip} '' ; do
	test -f $PKG$k.txz || continue
	tar ${V}xpf $PKG$k.txz -C /
	break
done

for k in -{zman,data} ; do
	test -f $PKG$k.txz || continue
	tar ${V}xpf $PKG$k.txz -C /
	break
done
