#! /bin/bash
set -exo nounset

rm $V -rf $INST
mkdir $V -p $INST/$PREFIX/bin
ln -s $BLD/gnulib-tool $INST/$PREFIX/bin/gnulib-tool
#test -d $INST || continue
pushd $INST
tar ${V}acpf $PKG.txz -C $INST .
popd
