#! /bin/bash
set -exo nounset

DIR=`mktemp -d`
trap "rm $V -rf $DIR" 0

for k in "$EXEC" $DATA ; do
	test -f $PKG$k.txz || continue
	tar ${V}xpf $PKG$k.txz -C $DIR
done

TEST_PATH=
for k in $DIR/{usr/{local/,},}{s,}bin ; do
	test -d $DIR/$k || continue
	TEST_PATH=$DIR/$k:$TEST_PATH
done

if test x$TEST_PATH == x ; then
	if test x$TEST == xnone ; then
		TEST_PATH=
	fi
fi
#test x$TEST_PATH != x || \
#test x$TEST == xnone && \
#TEST_PATH=
export TEST_PATH

$CIS/test-$TEST
